import { useRef,useState } from 'react';
import type { Question } from '../data/content';
import { ProgressBar,ResultCard,SourceReference } from './Shared';
import { useStageFocus } from '../hooks/useStageFocus';
import { useQuizTool } from '../hooks/useQuizTool';
type Lang='et'|'en'|'ru';
const t=(l:Lang,et:string,ru:string,en:string)=>l==='en'?en:l==='ru'?ru:et;
export function Quiz({questions,onComplete,lang}:{questions:Question[];onComplete?:(score:number)=>void;lang:Lang}){
 const [index,setIndex]=useState(0),[answers,setAnswers]=useState<boolean[]>([]),[done,setDone]=useState(false);const locked=useRef(false),nextRef=useRef<HTMLButtonElement>(null),heading=useStageFocus(done?'result':index);const score=answers.reduce((n,a,i)=>n+Number(a===questions[i].fact),0);
 useQuizTool({question:done?null:questions[index].statement,position:index+1,total:questions.length,answered:answers[index]!==undefined,completed:done,score});
 const answer=(value:boolean)=>{if(locked.current)return;locked.current=true;setAnswers(a=>[...a,value]);requestAnimationFrame(()=>nextRef.current?.focus({preventScroll:true}));};const next=()=>{if(index===questions.length-1){setDone(true);onComplete?.(score)}else{setIndex(i=>i+1);locked.current=false}};
 const q=questions[index];
 return <div className="quiz-card">{done?<><h3 ref={heading} tabIndex={-1}>{t(lang,'Sinu tulemus','Твой результат','Your result')}: {score} / {questions.length}</h3><ResultCard title={t(lang,'Teadmiste kontroll on tehtud','Проверка знаний завершена','Knowledge check completed')} score={score} total={questions.length} lang={lang}><p>{t(lang,'Vaata selgitused üle ja proovi soovi korral uuesti. Tulemus ei hinda sinu tervist.','Просмотри объяснения и при желании попробуй ещё раз. Результат не оценивает твоё здоровье.','Review the explanations and try again if you wish. The result does not assess your health.')}</p></ResultCard><button className="button primary" onClick={()=>{setIndex(0);setAnswers([]);setDone(false);locked.current=false}}>{t(lang,'Proovi viktoriini uuesti','Пройти викторину ещё раз','Take the quiz again')}</button></>:<><div className="quiz-top"><span className="pill">{t(lang,'MÜÜT VÕI FAKT?','МИФ ИЛИ ФАКТ?','MYTH OR FACT?')}</span><span>{String(index+1).padStart(2,'0')} / {String(questions.length).padStart(2,'0')}</span></div><ProgressBar value={answers.length} max={questions.length} label={t(lang,`${answers.length} vastust ${questions.length}-st lõpetatud`,`${answers.length} из ${questions.length} ответов завершено`,`${answers.length} of ${questions.length} answers completed`)}/><h3 className="quiz-statement" ref={heading} tabIndex={-1}>{q.statement}</h3><div className="quiz-choices"><button className="button" disabled={answers[index]!==undefined} onClick={()=>answer(false)}>{t(lang,'MÜÜT','МИФ','MYTH')}</button><button className="button" disabled={answers[index]!==undefined} onClick={()=>answer(true)}>{t(lang,'FAKT','ФАКТ','FACT')}</button></div>{answers[index]!==undefined&&<div className={'quiz-feedback '+(answers[index]===q.fact?'correct':'incorrect')} role="status"><strong>{answers[index]===q.fact?t(lang,'Õige vastus.','Верно.','Correct.'):t(lang,'Seekord läks teisiti.','На этот раз ответ другой.','Not this time.')} {q.fact?t(lang,'See on fakt.','Это факт.','This is a fact.'):t(lang,'See on müüt.','Это миф.','This is a myth.')}</strong><p>{q.explanation} <SourceReference ids={q.refs} lang={lang}/></p></div>}{answers[index]!==undefined&&<button ref={nextRef} className="button primary next" onClick={next}>{index===questions.length-1?t(lang,'Vaata tulemust','Посмотреть результат','View result'):t(lang,'Järgmine väide','Следующее утверждение','Next statement')}</button>}</>}</div>;
}

