import { useRef, useState } from 'react';
import type { Question } from '../data/content';
import { ProgressBar, ResultCard, SourceReference } from './Shared';
import { useStageFocus } from '../hooks/useStageFocus';
import { useQuizTool } from '../hooks/useQuizTool';
export function QuizQuestion({question,answer,onAnswer}:{question:Question;answer:boolean|undefined;onAnswer:(value:boolean)=>void}){return <><div className="quiz-choices"><button className={'button '+(answer===false?'selected':'')} disabled={answer!==undefined} onClick={()=>onAnswer(false)}>MÜÜT</button><button className={'button '+(answer===true?'selected':'')} disabled={answer!==undefined} onClick={()=>onAnswer(true)}>FAKT</button></div>{answer!==undefined&&<div className={'quiz-feedback '+(answer===question.fact?'correct':'incorrect')} role="status"><strong>{answer===question.fact?'Õige vastus.':'Seekord läks teisiti.'} {question.fact?'See on fakt.':'See on müüt.'}</strong><p>{question.explanation} <SourceReference ids={question.refs}/></p>{question.status!=='verified'&&<p>{question.status}</p>}</div>}</>;}
export function Quiz({questions,onComplete}:{questions:Question[];onComplete?:(score:number)=>void}){
 const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<boolean[]>([]);const [done,setDone]=useState(false);const locked=useRef(false);const heading=useStageFocus(done?'result':index);const nextRef=useRef<HTMLButtonElement>(null);
 const score=answers.reduce((sum,a,i)=>sum+Number(a===questions[i].fact),0);
 useQuizTool({question:done?null:questions[index].statement,position:index+1,total:questions.length,answered:answers[index]!==undefined,completed:done,score});
 const answer=(value:boolean)=>{if(locked.current)return;locked.current=true;setAnswers(a=>[...a,value]);requestAnimationFrame(()=>nextRef.current?.focus({preventScroll:true}));};
 const next=()=>{if(answers[index]===undefined)return;if(index===questions.length-1){setDone(true);onComplete?.(score);}else{setIndex(i=>i+1);locked.current=false;}};
 return <div className="quiz-card">{done?<><h3 ref={heading} tabIndex={-1}>Sinu tulemus: {score} / {questions.length}</h3><ResultCard title="Teadmiste kontroll on tehtud" score={score} total={questions.length}><p>Vaata selgitused üle ja proovi soovi korral uuesti. Tulemus ei hinda sinu tervist.</p></ResultCard><details><summary>Vaata kõiki vastuseid</summary><ol className="answer-review">{questions.map((q,i)=><li key={q.id}><strong>{q.statement}</strong><p>{q.fact?'Fakt':'Müüt'} · {answers[i]===q.fact?'Vastasid õigesti':'Sinu vastus oli vale'}. {q.explanation} <SourceReference ids={q.refs}/></p></li>)}</ol></details><button className="button primary" onClick={()=>{setIndex(0);setAnswers([]);setDone(false);locked.current=false;}}>Proovi viktoriini uuesti</button></>:<><div className="quiz-top"><span className="pill">MÜÜT VÕI FAKT?</span><span>{String(index+1).padStart(2,'0')} / {String(questions.length).padStart(2,'0')}</span></div><ProgressBar value={index} max={questions.length} label={`${index} vastust ${questions.length}-st lõpetatud`}/><h3 className="quiz-statement" ref={heading} tabIndex={-1}>{questions[index].statement}</h3><QuizQuestion question={questions[index]} answer={answers[index]} onAnswer={answer}/>{answers[index]!==undefined&&<button ref={nextRef} className="button primary next" onClick={next}>{index===questions.length-1?'Vaata tulemust':'Järgmine väide'} <span aria-hidden="true">→</span></button>}</>}</div>;
}
