import { useEffect, useRef, useState } from 'react';
import Brain from './sections/Brain';
import Memory from './sections/Memory';
import Attention from './sections/Attention';
import Closing from './sections/Closing';
import { Section } from './components/Shared';
import { Quiz } from './components/Quiz';
import { questions } from './data/content';
const links = [['avaleht','Avaleht'],['aju','Aju'],['malu','Mälu'],['tahelepanu','Tähelepanu'],['viktoriin','Müüt või fakt?'],['allikad','Allikad']];
export default function App(){
  const [menu,setMenu]=useState(false);
  const [active,setActive]=useState('avaleht');
  const menuButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id);},{rootMargin:'-15% 0px -65% 0px'});links.forEach(([id])=>{const el=document.getElementById(id);if(el)observer.observe(el);});return()=>observer.disconnect();},[]);
  return <><a className="skip" href="#sisu">Liigu põhisisu juurde</a><header className="header"><a className="brand" href="#avaleht"><span className="brand-mark" aria-hidden="true">a.</span> alkohol ja aju</a><button ref={menuButton} className="menu-toggle" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>Menüü {menu?'−':'+'}</button><nav onKeyDown={e=>{if(e.key==='Escape'){setMenu(false);menuButton.current?.focus();}}} id="navigation" aria-label="Peamenüü" className={menu?'open':''}>{links.map(([id,name])=><a key={id} aria-current={active===id?'location':undefined} href={'#'+id} onClick={()=>setMenu(false)}>{name}</a>)}</nav></header><main id="sisu" tabIndex={-1}><section id="avaleht" className="hero"><div className="hero-copy"><p className="eyebrow">UURI. KATSETA. MÕTESTA.</p><h1>Alkohol<br/>ja <span>aju.</span></h1><h2>Mis toimub mälu ja tähelepanuga alkoholi tarvitamisel?</h2><p>Vaata teaduse sisse. Proovi mälu ja tähelepanu harjutusi ning erista levinud müüte faktidest.</p><div className="actions"><a className="button primary" href="#aju">Alusta <span aria-hidden="true">↓</span></a><a className="text-link" href="#viktoriin">Testi oma teadmisi <span aria-hidden="true">↗</span></a></div><p className="hero-note">Õppematerjal gümnaasiumiõpilasele</p></div><div className="hero-visual"><div className="visual-top"><span>ÜKS AJU. MITU ÜLESANNET.</span><span aria-hidden="true">01 / 04</span></div><div className="signal" aria-hidden="true"><div className="signal-ring ring-one"/><div className="signal-ring ring-two"/><div className="signal-ring ring-three"/><span className="signal-core">aju</span><span className="signal-label label-one">Mälu</span><span className="signal-label label-two">Tähelepanu</span><span className="signal-label label-three">Reaktsioon</span><span className="signal-label label-four">Otsustamine</span></div><p>Meelde jätmine. Märkamine. Valikute tegemine.</p><div className="visual-bottom"><span>Avasta seosed</span><a href="#aju" aria-label="Uuri, mis toimub ajus">↓</a></div></div></section><div className="intro-strip"><span><b>01</b> Mõista aju</span><span><b>02</b> Proovi ise</span><span><b>03</b> Kontrolli teadmisi</span><span className="strip-note">Teadmine algab küsimusest.</span></div><Brain/><Memory/><Attention/><Section id="viktoriin" number="04 / KONTROLLI TEADMISI" title="Müüt või fakt?" intro="Kaheksa väidet. Otsusta, millised neist peavad paika, ja vaata iga vastuse selgitust." className="quiz-section"><Quiz questions={questions}/></Section><Closing/></main><footer>Alkohol ja aju <span>Gümnaasiumi praktiline töö</span></footer></>;
}
