import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './scrollProgress';
import './styles.css';
import './features.css';
import './visuals.css';
import './polish.css';
import './lab.css';
import './survey.css';
import './clarity.css';
import './lab-clarity.css';
import './learning.css';
import './final-polish.css';
import './stability.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
