import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './features.css';
import './visuals.css';
import './polish.css';
import './lab.css';
import './survey.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
