import { useEffect, useState } from 'react';
import ResearchApp from './ResearchApp';

type Lang='et'|'ru';
const languageKey='alkohol-ja-aju:language';
function readLang():Lang{try{return localStorage.getItem(languageKey)==='ru'?'ru':'et';}catch{return'et';}}

export default function ResearchExperience(){
  const [started,setStarted]=useState(false);
  const [lang,setLang]=useState<Lang>(readLang);
  const ru=lang==='ru';
  useEffect(()=>{document.documentElement.classList.toggle('research-started',started);return()=>document.documentElement.classList.remove('research-started');},[started]);
  if(started)return <ResearchApp/>;
  return <div className="research-shell research-intro-shell"><header className="research-header"><a className="research-brand" href="../"><img src="../logo-mark.svg" alt=""/><span>{ru?'алкоголь и мозг':'alkohol ja aju'}</span></a><a className="research-home" href="../">{ru?'На сайт':'Põhilehele'}</a><div className="research-lang"><button className={lang==='et'?'active':''} onClick={()=>{setLang('et');try{localStorage.setItem(languageKey,'et');}catch{}}}>ET</button><button className={lang==='ru'?'active':''} onClick={()=>{setLang('ru');try{localStorage.setItem(languageKey,'ru');}catch{}}}>RU</button></div></header><main className="research-intro-main"><section className="research-intro-card"><span className="research-kicker">{ru?'УЧЕБНО-ИССЛЕДОВАТЕЛЬСКИЙ ОПРОС · 15+':'ÕPPE- JA UURIMISKÜSITLUS · 15+'}</span><h1>{ru?'Перед началом — самое важное.':'Enne alustamist — kõige olulisem.'}</h1><div className="research-intro-facts"><article><strong>5–7 {ru?'минут':'minutit'}</strong><p>{ru?'Пять коротких шагов. Можно остановиться в любой момент до отправки.':'Viis lühikest sammu. Enne saatmist võid igal ajal lõpetada.'}</p></article><article><strong>{ru?'Без прямых идентификаторов':'Ilma otseste tunnusteta'}</strong><p>{ru?'Не спрашиваем имя, e-mail, телефон, школу или точную дату рождения.':'Me ei küsi nime, e-posti, telefoni, kooli ega täpset sünnikuupäeva.'}</p></article><article><strong>{ru?'Чувствительные вопросы':'Tundlikud küsimused'}</strong><p>{ru?'Можно выбрать «предпочитаю не отвечать» там, где это предусмотрено.':'Seal, kus see on ette nähtud, saad valida „eelistan mitte vastata“.'}</p></article><article><strong>{ru?'Два канала доставки':'Kaks saatmiskanalit'}</strong><p>{ru?'После отправки сервер отдельно пробует Google Sheets и Telegram и показывает результат каждого канала.':'Pärast saatmist proovib server eraldi Google Sheetsi ja Telegrami ning näitab kummagi tulemust.'}</p></article></div><div className="research-intro-note"><strong>{ru?'Если тебе 15–17':'Kui oled 15–17'}</strong><p>{ru?'В форме будет отдельное информированное подтверждение. Сама веб-форма не заменяет требования, которые могут применяться к конкретному исследованию.':'Vormis on eraldi teadlik kinnitus. Veebivorm ei asenda konkreetsele uuringule kohalduda võivaid nõudeid.'}</p></div><div className="research-intro-actions"><button className="research-primary" onClick={()=>setStarted(true)}>{ru?'Начать опрос':'Alusta küsitlust'}</button><a className="research-secondary" href="../data-policy/">{ru?'Как используются данные':'Kuidas andmeid kasutatakse'}</a><a className="research-secondary" href="results/">{ru?'Публичные результаты':'Avalikud tulemused'}</a></div></section></main></div>;
}
