const ALLOWED_ORIGINS=new Set(['https://alco-uurimis.github.io','https://alkohol-ja-aju.vercel.app']);
const MIN_GROUP=10;
const GROUP_KEYS=['ageGroup','ownUse','overallImpact','helpKnowledge'];
function cors(req,res){const origin=req.headers?.origin;if(origin&&ALLOWED_ORIGINS.has(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','public, max-age=300, s-maxage=300');}
async function fetchWithTimeout(url,options,timeoutMs=45000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timer);}}
async function postToAppsScript(url,body){const options={method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),redirect:'manual'};const first=await fetchWithTimeout(url,options);if(![301,302,303,307,308].includes(first.status))return first;const location=first.headers.get('location');if(!location)throw new Error('apps_script_redirect_missing');const destination=new URL(location,url).toString();return [307,308].includes(first.status)?fetchWithTimeout(destination,options):fetchWithTimeout(destination,{method:'GET',headers:{accept:'application/json'}});}
function cleanGroup(value){if(!value||typeof value!=='object'||Array.isArray(value))return{};const out={};for(const [key,count] of Object.entries(value)){const n=Number(count);if(Number.isInteger(n)&&n>=MIN_GROUP)out[String(key).slice(0,80)]=n;}return out;}
function publicSummary(data){const n=Math.max(0,Number.isFinite(Number(data?.n))?Math.trunc(Number(data.n)):0);const minimumGroupSize=Math.max(MIN_GROUP,Number.isFinite(Number(data?.minimumGroupSize))?Math.trunc(Number(data.minimumGroupSize)):MIN_GROUP);const base={ok:true,schemaVersion:4,n,publishable:n>=minimumGroupSize,minimumGroupSize,lastUpdated:typeof data?.lastUpdated==='string'?data.lastUpdated:new Date().toISOString()};if(!base.publishable)return base;for(const key of GROUP_KEYS)base[key]=cleanGroup(data?.[key]);return base;}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({ok:false,error:'method_not_allowed'});const origin=req.headers?.origin;if(origin&&!ALLOWED_ORIGINS.has(origin))return res.status(403).json({ok:false,error:'origin_not_allowed'});const url=process.env.SHEET_WEBHOOK_URL,secret=process.env.SHEET_WEBHOOK_SECRET;if(!url||!secret)return res.status(503).json({ok:false,error:'summary_not_configured'});try{const parsed=new URL(String(url).trim());if(parsed.protocol!=='https:'||parsed.hostname!=='script.google.com')return res.status(503).json({ok:false,error:'summary_url_invalid'});const response=await postToAppsScript(parsed.toString(),{secret,aggregate:true,schemaVersion:4});const text=await response.text();let data={};try{data=JSON.parse(text);}catch{}const validCount=Number.isFinite(Number(data?.n));const upstreamAccepted=data?.ok===true||data?.ok==='true';if(!response.ok||!upstreamAccepted||!validCount)return res.status(502).json({ok:false,error:'summary_upstream_failed',status:response.status});return res.status(200).json(publicSummary(data));}catch(error){return res.status(502).json({ok:false,error:error?.name==='AbortError'?'summary_timeout':'summary_unreachable'});}}

